"project_id" : "417706"
"api_token" : "c171d67a29cd6676859dc21b11551db2bf38e122eddea7f3deff444c8b3ee69351bf62815a90799d"
"base_path" : "/Users/DanielleSerejo/Desktop/vtex/crowdin/apps/product-price"
files: [
 {
  "source" : "/messages/en.json",
  "translation" : "/messages/%locale%.json",
  "type" : "json",
 }
]
